version: '2'
services:
	stats-ai-api:
		build: .
		ports:
			- 8787:8787
			- 8080:8080
		environment:
			RUNTIME_ENV: dev
			ENVIRONMENT: dev
		volumes:
			- ./build/libs/:/deployment/
		image: stats-ai-api-image 